### ISSUE TITLE
Binder not lauching

### ISSUE THREAD

**Issue by mathieuboudreau** [FINKI-Research-methodology-in-ICT/Notebooks#2]
I added a binder button to the README, but it's not launching for me for some reason. I tried other binder buttons on other repos and they work, so not quite sure why this one is hanging up. Is it just me?

**Comment by mathieuboudreau** [comment]
@agahkarakuzu 🔴

**Comment by agahkarakuzu** [comment]
It works  building atm 👀 

![image](https://user-images.githubusercontent.com/9632322/65633193-8f68fc00-dfa9-11e9-8a87-7e2297d18b33.png)

**Comment by mathieuboudreau** [comment]
Cool! Must have just been me then. Thanks!
